name: CICD

on: 
    workflow_dispatch:

jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name:  clone the code
          run:   echo "cloning the code"

    build:
      runs-on: ubuntu-latest
      steps:
        - name:  build the code using Docker
          run:  echo "build the code using Docker"  

    test:
      runs-on: ubuntu-latest
      steps:
        - name: Running tests cases
          run: echo "testing the App"

    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: deploying on machine
          run: echo "deploying the code"

          

          
    
    
            




